const styles = {
  // ===== PAGE LAYOUT =====
  page: {
    minHeight: '100vh',
    backgroundColor: '#fafafd',
    padding: '2rem 3rem',
    fontFamily: "'Inter', 'Poppins', Arial, sans-serif", // modern font stack
    color: '#26233a',
    fontSize: '16px',
  },

  // ===== HEADER & TABS =====
  header: { marginBottom: '1.5rem' },
  mainTitle: {
    fontFamily: "'Poppins', 'Inter', sans-serif",
    fontSize: '2.2rem',
    fontWeight: '800',
    margin: 0,
    color: '#232241',
    letterSpacing: '0.01rem',
  },
  subtitle: {
    color: '#76768a',
    fontSize: '1rem',
    marginTop: '0.6rem',
    marginLeft: '0.4rem',
    fontWeight: '500',
  },
  tabsRow: { display: 'flex', gap: '1rem', marginTop: '2rem', marginBottom: '3rem' },
  tab: {
    padding: '0.5rem 1.2rem',
    borderRadius: '0.75rem',
    fontWeight: '700',
    cursor: 'pointer',
    backgroundColor: 'white',
    border: '2px solid #ede6ff',
    boxShadow: '0 0 8px #ebe9f5',
    fontFamily: "'Inter', sans-serif",
  },

  // ===== MAIN GRID =====
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit,minmax(350px,1fr))',
    gap: '2rem',
  },

  // ===== CARD STYLING =====
  card: {
    backgroundColor: 'white',
    borderRadius: '1.35rem',
    padding: '2rem 2rem 1.5rem 2rem',
    boxShadow: '0 4px 15px rgba(151,96,255,0.06)',
    border: '1px solid #ece9fc',
    display: 'flex',
    flexDirection: 'column',
    gap: '1.1rem',
    transition: 'transform 0.38s cubic-bezier(.24,1,.32,1), box-shadow 0.38s cubic-bezier(.24,1,.32,1)',
    cursor: 'pointer',
    fontFamily: "'Inter', 'Poppins', sans-serif",
    position: 'relative',
    zIndex: 0,
  },
  cardHover: {
    transform: 'translateY(-8px) scale(1.04)',
    boxShadow: '0 14px 32px rgba(151,96,255,0.14)',
    zIndex: 2,
  },
  cardHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    marginBottom: '0.8rem',
  },
  title: {
    fontWeight: '700',
    fontSize: '1.12rem',
    color: '#322957',
    fontFamily: "'Poppins', 'Inter', sans-serif",
    letterSpacing: '0.01em',
  },
  description: {
    color: '#6d6681',
    fontSize: '0.98rem',
    fontFamily: "'Inter', sans-serif",
    fontWeight: '500',
    letterSpacing: '0.01em',
  },
  iconBackground: {
    padding: '0.55rem',
    borderRadius: '50%',
    backgroundColor: 'rgba(154, 86, 255, 0.11)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tag: {
    padding: '0.22rem 0.7rem',
    borderRadius: '0.55rem',
    fontWeight: '700',
    fontSize: '0.74rem',
    color: '#9760ff',
    backgroundColor: '#ebe6ff',
    fontFamily: "'Inter', sans-serif",
  },

  // ===== IMAGE STYLING =====
  thumbnailContainer: {
    position: 'relative',
    width: '100%',
    height: '180px',
    borderRadius: '0.95rem',
    overflow: 'hidden',
    boxShadow: '0 4px 12px rgba(151,96,255,0.08)',
    transition: 'transform 0.4s cubic-bezier(.24,1,.32,1), box-shadow 0.4s cubic-bezier(.24,1,.32,1)',
  },
  thumbnail: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    transition: 'transform 0.8s cubic-bezier(.24,1,.32,1)',
  },
  statusBadge: {
    position: 'absolute',
    bottom: '10px',
    right: '10px',
    padding: '0.3rem 0.7rem',
    borderRadius: '0.55rem',
    fontWeight: '600',
    fontSize: '0.76rem',
    backgroundColor: '#fff',
    boxShadow: '0 2px 7px rgba(151,96,255,0.09)',
    fontFamily: "'Inter', sans-serif",
  },

  // ===== BUTTON STYLING =====
  startButton: {
    marginTop: '1rem',
    backgroundColor: '#9760ff',
    borderRadius: '0.95rem',
    border: 'none',
    padding: '0.8rem 0',
    fontWeight: '700',
    fontSize: '1rem',
    color: '#fff',
    cursor: 'pointer',
    transition: 'transform 0.24s ease, background-color 0.3s ease, box-shadow 0.3s ease',
    boxShadow: '0 4px 12px rgba(151,96,255,0.18)',
    fontFamily: "'Poppins', 'Inter', sans-serif",
    letterSpacing: '0.01em',
  },
  startButtonHover: {
    backgroundColor: '#8253e6',
    transform: 'translateY(-2px) scale(1.02)',
    boxShadow: '0 7px 16px rgba(151,96,255,0.21)',
  },
  startButtonActive: {
    transform: 'scale(0.97)',
  },

  // ===== QUICK ACTIONS =====
  quickActionsContainer: {
    marginTop: '2.5rem',
    background: '#fff',
    borderRadius: '1.2rem',
    padding: '1.5rem 2rem',
    boxShadow: '0 3px 14px 0 rgba(151, 96, 255, 0.05)',
    border: '1px solid #eee',
    fontFamily: "'Inter', sans-serif",
  },
  quickActionsTitle: {
    fontWeight: 800,
    fontSize: '1.15rem',
    marginBottom: '0.25rem',
    color: '#232241',
    fontFamily: "'Poppins', 'Inter', sans-serif",
    letterSpacing: '0.01em',
  },
  quickActionsSubtitle: {
    marginBottom: '1.05rem',
    color: '#7b7e8c',
    fontSize: '0.93rem',
    fontWeight: 500,
    fontFamily: "'Inter', sans-serif",
  },
  quickActionsGrid: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '1.1rem',
    justifyContent: 'flex-start',
  },
  quickActionButton: {
    background: '#fafafd',
    border: 'none',
    borderRadius: '2rem',
    padding: '0.8rem 2rem',
    fontWeight: '700',
    color: '#2f2548',
    fontSize: '1.06rem',
    letterSpacing: '0.01em',
    transition: 'background 0.19s, box-shadow 0.19s, transform 0.2s',
    boxShadow: '0 1px 4px 0 rgba(151, 96, 255, 0.08)',
    display: 'flex',
    alignItems: 'center',
    gap: '0.7rem',
    outline: 'none',
    cursor: 'pointer',
    minWidth: '140px',
    justifyContent: 'center',
    fontFamily: "'Poppins', 'Inter', sans-serif",
  },

  // ===== TABLE & ANALYTICS =====
  analyticsOverview: { marginTop: '2rem' },
  analyticsOverviewGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: "1.5rem",
  },
  analyticsOverviewCard: {
    backgroundColor: "white",
    borderRadius: "1rem",
    padding: "1.5rem",
    boxShadow: "0 3px 14px rgba(151,96,255,0.09)",
    textAlign: "center",
    border: "1px solid #ece9fc",
    transition: "transform 0.27s cubic-bezier(.24,1,.32,1), box-shadow 0.27s cubic-bezier(.24,1,.32,1)",
    fontFamily: "'Poppins', 'Inter', sans-serif",
    fontWeight: 600,
  },
  analyticsOverviewCardHover: {
    transform: "translateY(-4px) scale(1.02)",
    boxShadow: "0 8px 24px rgba(151,96,255,0.13)",
  },
  analyticsValue: {
    fontSize: "2.1rem",
    fontWeight: "800",
    color: "#9760ff",
    fontFamily: "'Poppins', 'Inter', sans-serif",
  },
  analyticsLabel: {
    marginTop: "0.45rem",
    color: "#555",
    fontWeight: "600",
    fontSize: "0.93rem",
    fontFamily: "'Inter', sans-serif",
  },
  sectionTitle: {
    fontWeight: "700",
    fontSize: "1.08rem",
    marginBottom: "1rem",
    color: "#444",
    fontFamily: "'Poppins', 'Inter', sans-serif",
    letterSpacing: '0.01em',
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    borderRadius: "0.75rem",
    overflow: "hidden",
    boxShadow: "0 1px 8px rgba(151,96,255,0.10)",
    fontFamily: "'Inter', sans-serif",
  },
  th: {
    backgroundColor: "#f8f6ff",
    color: "#555",
    textAlign: "left",
    padding: "0.75rem 1rem",
    fontWeight: "700",
    fontSize: "0.97rem",
    borderBottom: "1px solid #eee",
    fontFamily: "'Poppins', 'Inter', sans-serif",
  },
  tr: {
    borderBottom: "1px solid #f3f3f3",
    transition: "all 0.19s cubic-bezier(.24,1,.32,1)",
  },
  td: {
    padding: "0.8rem 1rem",
    fontSize: "0.97rem",
    color: "#322957",
    fontFamily: "'Inter', sans-serif",
  },
};

export default styles;
