const styles = {
  page: { minHeight: '100vh', backgroundColor: '#fafafd', padding: '2rem 3rem' },
  header: { marginBottom: '1rem' },
  titleRow: { display: 'flex', alignItems: 'center', gap: '0.5rem' },
  titleIconBackground: { backgroundColor: '#ede6ff', padding: '0.3rem', borderRadius: '50%' },
  mainTitle: { fontSize: '2rem', fontWeight: '900', margin: 0 },
  badgeRow: { display: 'flex', gap: '0.5rem', marginTop: '0.5rem' },
  badge: { padding: '0.2rem 0.5rem', borderRadius: '100px', fontWeight: '700', fontSize: '0.75rem' },
  badgeGreen: { backgroundColor: '#e3f9e5', color: '#05944f' },
  badgeGray: { backgroundColor: '#f7f7f7', color: '#999' },
  subtitle: { color: '#666', fontSize: '0.9rem', marginTop: '0.5rem', marginLeft: '0.4rem' },
  tabsRow: { display: 'flex', gap: '1rem', marginTop: '2rem', marginBottom: '3rem' },
  tab: {
    padding: '0.5rem 1.2rem',
    borderRadius: '0.75rem',
    fontWeight: '700',
    cursor: 'pointer',
    backgroundColor: 'white',
    border: '2px solid #ede6ff',
    boxShadow: '0 0 8px #ebe9f5',
  },
  grid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(350px,1fr))', gap: '2rem' },
  card: {
    backgroundColor: 'white',
    borderRadius: '1.25rem',
    padding: '1.5rem 2rem',
    boxShadow: '0 2px 16px rgb(217 210 237 / 0.12)',
    border: '1px solid #ebe9f5',
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    transition: 'all 0.25s ease',
  },
  cardHover: { boxShadow: '0 15px 40px rgb(217 210 237 / 0.3)', transform: 'translateY(-6px) scale(1.012)' },
  cardHeader: { display: 'flex', alignItems: 'center', gap: '0.7rem' },
  iconBackground: { padding: '0.5rem', borderRadius: '50%', backgroundColor: 'rgba(154, 86, 255, 0.1)' },
  tag: { padding: '0.2rem 0.6rem', borderRadius: '0.55rem', fontWeight: '700', fontSize: '0.7rem', color: '#9760ff', backgroundColor: '#ebe6ff' },
  title: { fontWeight: '700', fontSize: '1.1rem' },
  description: { color: '#666', marginLeft: '3.5rem', fontSize: '0.9rem' },
  confidenceLabel: { marginLeft: '3.5rem', color: '#8b8b8b', fontSize: '0.75rem' },
  progressBarBackground: { width: '100%', height: '8px', backgroundColor: '#ebe6ff', borderRadius: '6px' },
  progressBar: { height: '8px', backgroundColor: '#9760ff', borderRadius: '6px', transition: 'width 0.3s ease-in-out' },
  progressPercent: { marginLeft: '0.5rem', color: '#9760ff', fontWeight: '700', fontSize: '0.8rem' },
  startButton: {
    marginTop: '1rem',
    backgroundColor: '#c7b8ff',
    borderRadius: '0.9rem',
    border: 'none',
    padding: '0.7rem 0',
    fontWeight: '700',
    color: '#fff',
    cursor: 'pointer',
  },
  quickActionsContainer: { marginTop: '3rem', backgroundColor: 'white', borderRadius: '1rem', padding: '1.5rem 2.5rem' },
  quickActionsTitle: { fontWeight: '700', fontSize: '1.2rem', marginBottom: '0.8rem' },
  quickActionsSubtitle: { marginBottom: '1.5rem', color: '#999' },
  quickActionsGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(160px, 1fr))', gap: '1rem' },
  quickActionButton: { background: '#fafafd', borderRadius: '1rem', padding: '1rem 0', border: '1px solid #e6e6f7', cursor: 'pointer' },
};

export default styles;
